### ISSUE TITLE
혹시 아래 에러 메시지 원인을 알려주실 수 있으신 가요?

### ISSUE THREAD

**Issue by agate20** [TechOrgg/ai_speaker4_watson#4]
@.@ STARTED !!  3200
Broker unavailable (3)
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
        at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:988)
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:145)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
@.@ SHUTDOWN...

**Comment by Choi-Eui-Shin** [comment]
네트워크 문제가 아니라면 다음을 실행해 보세요.
mqtt/bin/hiot 폴더 밑에 tmp, data 폴더가 있습니다.
각각의 폴더 아래에서 sudo rm 명령어로 파일을 삭제하시고 리스타트 해보세요.

**Comment by agate20** [comment]
말씀해 주신 방법으로 해결하였습니다. 
하지만 문제가 하나 더 생겼는데요. 
아래와 같이 DB에 리모컨 데이터도 넣은 후, "텔레비전 꺼죠" 라는 명령어를 말하니 문제가 발생하였습니다.  
![image](https://user-images.githubusercontent.com/14942441/43188138-5e64277c-902e-11e8-8994-8487e7d52990.png)

아래와 같은 에러 메세지입니다. 
@.@ STT : 텔레비젼 꺼줘 
Jul 25, 2018 4:57:40 PM okhttp3.internal.platform.Platform log
INFO: --> POST https://gateway.watsonplatform.net/conversation/api/v1/workspaces/86d2a7f6-70b1-4902-a3e8-924d7e09d290/message?version=2018-02-16 http/1.1 (414-byte body)
Jul 25, 2018 4:57:40 PM okhttp3.internal.platform.Platform log
INFO: <-- 200 OK https://gateway.watsonplatform.net/conversation/api/v1/workspaces/86d2a7f6-70b1-4902-a3e8-924d7e09d290/message?version=2018-02-16 (421ms, 475-byte body)
>> @DEV_CNTR[target] target/tv
>> @DEV_CNTR[action] action/turnoff
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at com.mycode.SimpleControlAction.getSingleIR(SimpleControlAction.java:156)
        at com.mycode.SimpleControlAction.controlDevice(SimpleControlAction.java:105)
        at com.mycode.SimpleControlAction.executeAction(SimpleControlAction.java:49)
        at com.mycode.MyBaseAction.execute(MyBaseAction.java:63)
        at com.klab.svc.BaseAction.doAction(Unknown Source)
        at com.klab.svc.SimpleAppFrame.a(Unknown Source)
        at com.klab.svc.SimpleAppFrame.a(Unknown Source)
        at com.klab.svc.SimpleAppFrame.message(Unknown Source)
        at com.svc.AiSpeakerAgent.processText(AiSpeakerAgent.java:363)
        at com.svc.AiSpeakerAgent.onTranscription(AiSpeakerAgent.java:449)
        at com.ibm.watson.developer_cloud.speech_to_text.v1.websocket.SpeechToTextWebSocketListener.onMessage(SpeechToTextWebSocketListener.java:129)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:307)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalStateException: Not a JSON Object: null
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
        at com.klab.svc.SimpleAppFrame.a(Unknown Source)
        at com.klab.svc.SimpleAppFrame.a(Unknown Source)
        at com.klab.svc.SimpleAppFrame.message(Unknown Source)
        at com.svc.AiSpeakerAgent.processText(AiSpeakerAgent.java:363)
        at com.svc.AiSpeakerAgent.onTranscription(AiSpeakerAgent.java:449)
        at com.ibm.watson.developer_cloud.speech_to_text.v1.websocket.SpeechToTextWebSocketListener.onMessage(SpeechToTextWebSocketListener.java:129)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:307)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

혹시 원인을 알 수 있을 까요?
